### ISSUE TITLE
Ubuntu use

### ISSUE THREAD

**Issue by grandchamp** [matgr1/FreeImage-dotnet-core#1]
It's possible to use on ubuntu?

**Comment by grandchamp** [comment]
Pr #2 sent.

**Comment by varnav** [comment]
How to use it on Ubuntu?

I have Ubuntu 16.04 LTS. I ran `apt install libfreeimageplus3` but it still complans:

> unable to load DLL 'libfreeimage'

**Comment by matgr1** [comment]
I haven't run this on Linux for a while, but I have libfreeimage3 (without the "plus") installed on my Ubuntu vm and I think that worked for me

**Comment by varnav** [comment]
libfreeimageplus3 [depends on libfreeimage3](https://packages.ubuntu.com/ru/xenial/libfreeimageplus3) so it's get installed too.
Anything I can do to help with diagnosing?

Also I see there is a [symlinking mentioned](https://github.com/matgr1/FreeImage-dotnet-core/pull/2#issuecomment-270087725). Is it necessary?

**Comment by grandchamp** [comment]
`sudo apt-get install libfreeimage3 libfreeimage-dev` always worked for me.

**Comment by varnav** [comment]
Looks like that 'dev' part helped, thanks. I thing it worth documenting.
