### ISSUE TITLE
Conflicts with System.Drawing.Primitives

### ISSUE THREAD

**Issue by saucecontrol** [matgr1/FreeImage-dotnet-core#4]
I'm having trouble using FreeImage in a project with another library that uses [System.Drawing.Primitives](https://www.nuget.org/packages/System.Drawing.Primitives/) because System.Drawing-dotnet-core defines several conflicting types (looks like all the geometry ones).

Any chance you could use those types from System.Drawing.Primitives and remove them from your System.Drawing-dotnet-core shim?

**Comment by matgr1** [comment]
done! let me know if I missed anything

**Comment by cwingram** [comment]
Awesome!  Thanks for the quick work

**Comment by saucecontrol** [comment]
Awesome! Thanks for the quick work
