### ISSUE TITLE
LoadEx not working in Linux 

### ISSUE THREAD

**Issue by varnav** [matgr1/FreeImage-dotnet-core#5]
Hello!

For me LoadEx always throws FileNotFoundException in Linux, while in Windows it works fine.

Anything I can do to help with debugging?

**Comment by CShepartd** [comment]
Are you trying mono or core?

**Comment by varnav** [comment]
Core

**Comment by CShepartd** [comment]
Cuz[ `LoadEx` using `Load`](https://github.com/matgr1/FreeImage-dotnet-core/blob/master/src/FreeImage-dotnet-core/FreeImageWrapper.cs#L1067). Why `Load` and `Save` working only in Windows i said there https://github.com/matgr1/FreeImage-dotnet-core/issues/3#issuecomment-321263026

**Comment by matgr1** [comment]
#3
